version: '3.7'

services:
  python-service: # Cux
    build: ./Python
    # image: robertocux1/microservicio2
    # Exponemos el puerto 80 para que sea accesible para los otros servicios.
    expose:
      - "5000"
    ports: 
      - "5000:5000"
    depends_on:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: password
      #MYSQL_DATABASE: ${MYSQL_DATABASE}
      # MYSQL_USER: ${MYSQL_USER}
      #MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      #MYSQL_HOST: ${MYSQL_HOST}
      #MYSQL_PORT: ${MYSQL_PORT}

  database:
    image: mongo:latest
    #command: mysqld --default-authentication-plugin=mysql_native_password
    volumes: # En caso de tener problemas con el voúmen, correr el siguiente comando: docker-compose rm -fv;
        - ./dbdata:/dbdata
    expose: 
      - "27017"
      - "27019"
    # Para mapear el contenedor a nuestra computadora podemos descomentar la siguiente línea
    ports:
        - "27017:27017"
        - "27019:27019"
    environment:
        MYSQL_ROOT_PASSWORD: password
        #MYSQL_DATABASE: ${MYSQL_DATABASE}
        # MYSQL_USER: ${MYSQL_USER}
        #MYSQL_PASSWORD: ${MYSQL_PASSWORD}
